### ISSUE TITLE
Firework crafting

### ISSUE THREAD

**Issue by therealDRCheese** [celsiusqc/Create-Dimensions#1]
I cant craft fireworks with colors

**Comment by celsiusqc** [comment]
I'll look into it. Can you send a screenshot of the recipe you are inputting while trying to make colored fireworks?

**Comment by therealDRCheese** [comment]
i am trying replacing the diamond dust with a fireworkstar with colors i am trying to place it beside the diamond dust i am trying to craft the firework and star together

**Comment by celsiusqc** [comment]
Because the firework recipes are all hard coded in the game, i had to force remove them with crafttweaker. I then added 3 recipes for 3 strengths of fireworks with my custom recipe to use the special dusts to make fireworks harder to acquire for elytra flight.

I have to find a workaround, but that may take a little time. What were you needing the colored / firework star versions for?

**Comment by therealDRCheese** [comment]
i wanted to use it for a crossbow and i wanted a firework show

**Comment by celsiusqc** [comment]
Fixed with upcoming major version
